# This is a basic workflow to help you get started with Actions

name: auto_juejin

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "18 0 * * *" # 该时间为UTC时间，比北京时间晚8个小时

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          COOKIE: 681c66152b0b4f528df3d66940915e86
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
        run: npm ci && node index.js "${COOKIE}" "${USER}" "${PASS}" "${TO}"
